Добавил логику аренды и комментарии. Прикрутил бд в проект.
KartmanJ/java-shareit pull request #2
Opened 2022-11-09 19:10 UTC by KartmanJ

2022-11-10 22:06 UTC, Fleaman777 requested changes

2022-11-10 22:06 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingDto add(@RequestBody @Valid BookingDtoInput bookingDto,
X-Sharer-User-Id можно было бы вынести в константу

аналогично в похожих местах

2022-11-10 22:06 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +                .build();
Правильно, что для большого количества просечивания используешь билдер

2022-11-10 22:06 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            " order by b.start")
Как ещё вариант, сделать запросы не через query запрос, а через специальные метода Спринг jpa, 
Должно получится покороче и возможно попонятней

2022-11-10 22:06 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    .filter(e -> e.getEnd().isAfter(LocalDateTime.now()))
Логику из 2х методов filter можно было бы вынести в отдельный вспомогательный метод с подходящим названием, тогда бы нам не пришлось создавать два фильтера и из названия бегло, можно было бы понять суть фильтра

2022-11-12 15:08 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingDto add(@RequestBody @Valid BookingDtoInput bookingDto,
Сделано

2022-11-12 15:08 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +                .build();
Иначе была бы каша, а не код)

2022-11-12 15:09 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            " order by b.start")
Переделал. Стало не намного понятнее, но компактнее)

2022-11-12 15:12 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    .filter(e -> e.getEnd().isAfter(LocalDateTime.now()))
Не знаю зачем, но сделал. В самом условии "Current" - текущие, должно читающего направить на мысль, зачем тут 2 фильтра. Вообще изначально был 1(с условием И), но скриптовый тест maven'а в проверках на GitHub попросил меня разбить на 2 фильтра.

2022-11-17 18:49 UTC, merged