Добавил запросы на аренду.
KartmanJ/java-shareit pull request #3
Opened 2022-11-23 18:34 UTC by KartmanJ

2022-11-27 09:21 UTC, Fleaman777 requested changes

2022-11-27 09:21 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    + ") был успешно получен.");
в сообщение для логирования лучше использовать плейсхолдеры {} , 
так и код будет лучше восприниматься, 
и чуть побыстрее работать, т.к информация в плейсхолдеры будет добавляться только тогда, когда этот лог будет выполнен, в отличие от обычной конкатенации, которая будет выполнятся всегда  

относится ко всем похожим местам

2022-11-27 09:21 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void isBookingExistsCheck(Long bookingId) {
хорошие методы проверки, 
но название можно сократить до isItemExist и isBookingExist 

т.к. по глаголу is в начале названия можно понять, что метод возвращает булиан, а значит внутри него будет какая-та проверка

аналогично в других похожих местах

2022-11-27 09:21 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +                .requestId(itemRequest.getId())
отличное применение билдера, когда нужно просетать много полей

2022-11-27 09:21 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        return itemRequestsPageable;
эту логику внутри foreach хорош было бы вынести в отдельный метод, для улучшения восприятия кода

2022-11-27 09:21 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank(message = "Адрес электронной почты не может быть пустым.")
отличное применение валидационных аннотаций

2022-11-27 09:21 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/ShareItAppTest.java
> +    }
интересный тест) 

но на самом деле, тест на App класс можно не писать, т.к. по сути, в этом классе нет никакой логики, которую нужно было бы проверять

2022-11-27 09:21 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingServiceImpl bookingService;
в тестах тоже принято придерживаться принципа инкапсуляции, 
поэтому хорошо добавлять модификатор private

2022-11-27 09:21 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 3L))
в тестах X-Sharer-User-Id тоже можно вынести в константу

2022-11-27 09:52 UTC, KartmanJ commented on src/test/java/ru/practicum/shareit/ShareItAppTest.java
> +    }
Чисто тест для покрытия)

2022-11-27 10:32 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    + ") был успешно получен.");
Поправил.

2022-11-27 10:32 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private void isBookingExistsCheck(Long bookingId) {
Поправил.

2022-11-27 10:32 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +                .requestId(itemRequest.getId())
Спасибо, стараюсь!

2022-11-27 10:33 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/request/service/RequestService.java
> +        return itemRequestsPageable;
Сделал.

2022-11-27 10:33 UTC, KartmanJ commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotBlank(message = "Адрес электронной почты не может быть пустым.")
Спасибо!

2022-11-27 10:33 UTC, KartmanJ commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingServiceImpl bookingService;
Исправил!

2022-11-27 10:34 UTC, KartmanJ commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 3L))
И тут тоже поправил. Спасибо за ревью!

2022-11-28 13:35 UTC, Fleaman777 approved these changes

2022-11-28 13:35 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    booking.getItem().getName(), booking.getItem().getId());
во, супер, вовсем другой вид

2022-12-03 11:05 UTC, merged