Контейнеризация проекта. Валидация вынесена в отдельный модуль.
KartmanJ/java-shareit pull request #4
Opened 2022-12-04 21:28 UTC by KartmanJ

2022-12-05 17:30 UTC, Fleaman777 requested changes

2022-12-05 17:30 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
если название параметра name совпадает с названием аргумента, то такой параметр можно не указывать. 

относится ко всем похожим местам

2022-12-05 17:30 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +@Validated
здорово, что решил сделать валидацию через аннотации, так код становится чище и понятней

2022-12-05 17:30 UTC, Fleaman777 commented on server/Dockerfile
> +FROM amazoncorretto:11-alpine-jdk
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,

то же относится и к docker-compose

2022-12-05 17:30 UTC, Fleaman777 commented on server/src/main/resources/application.properties
>  spring.datasource.username=test
сейчас получается, что значения переменных окружения, используются те, которые указаны в application.properties, а не те, которые в docker-compose

например в application.properties ,
можно использовать такую конструкцию: spring.datasource.username=${POSTGRES_USER:test}
она означает, что если, в докер-компосе не просетать переменную POSTGRES_USER, то будет использоваться дефлотное значение test

2022-12-05 18:37 UTC, KartmanJ commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
это часть предложенного Практикумом шаблонного кода) Я обычно так и прописываю параметры и аргументы - с идентичными названиями, но тут просто не стал править, придерживаясь правила - "работает - не трогай") Поправлю)

2022-12-05 18:38 UTC, KartmanJ commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +@Validated
Она вроде и была в аннотациях вся...

2022-12-05 19:19 UTC, KartmanJ commented on server/src/main/resources/application.properties
>  spring.datasource.username=test
Хорошее замечание, спасибо!

2022-12-06 15:44 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
аа, понятно, в целом неплохой подход, 
но если видишь моменты, которые можно было бы исправить, тем самым улучшив качество кода, можно исправлять - по хорошему, исправить и ничего не поломать должны помочь тесты)
но всякое бывает, поэтому хорошо что решил перестраховаться и на всякий случай не править)

2022-12-06 15:45 UTC, Fleaman777 approved these changes

2023-01-05 15:38 UTC, merged